name: ragcdl
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.17
  - pip=25.2
  - python=3.12.11
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - filelock==3.19.1
      - fsspec==2025.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.2
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.3
      - packaging==25.0
      - pandas==2.3.2
      - pathlib==1.0.1
      - pillow==11.3.0
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentence-transformers==5.1.1
      - six==1.17.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - tqdm==4.67.1
      - transformers==4.56.2
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      # === AJOUTS POUR CHROMADB ===
      - chromadb==1.1.1
      - hnswlib>=0.7.0
      - pydantic==2.12.3

      # === OPENAI + HTTPX (compatibles ensemble) ===
      - openai==2.6.1      # OpenAI 2.x
      - httpx>=0.27.0,<0.28.0     # Éviter 0.28.0
      - httpcore>=1.0.0,<2.0.0    # Dépendance stable

      # === AJOUTS POUR TESSERACT OCR ===
      - pytesseract==0.3.13
      - pdf2image==1.17.0
      - opencv-python==4.10.0.84
      - pymupdf==1.25.5
      - python-docx==1.1.0 # Pour manipuler les documents Word
      - pycryptodome

      # === AJOUT POUR LANGCHAIN ===
      - langchain == 1.0.3
      - langchain-text-splitters==1.0.0
      - langchain-community>=0.0.1

      # === AJOUTS POUR LLMs LOCAUX === 
      - llama-cpp-python
      - sse-starlette
      - starlette-context
      - fastapi
      - uvicorn

